#!/bin/bash

# Source directory
source="/Users/codycf/Desktop/arvo/tutorials/Conceptual_Guide/Part_1-model_deployment/model_repository/text_recognition/1"

# Destination directory
destination="/Users/codycf/Desktop/arvo/bridge/src/backend/models"

# File to be moved
file_to_move="text_recognition.onnx"  # Change this to the name of the file you want to move

# Move the file
cp "${source}/${file_to_move}" "${destination}"


# Source directory
source="/Users/codycf/Desktop/arvo/tutorials/Conceptual_Guide/Part_1-model_deployment/model_repository/text_recognition"

# Destination directory
destination="/Users/codycf/Desktop/arvo/bridge/src/backend/configs"

# File to be moved
file_to_move="text_recognition.pbtxt"  # Change this to the name of the file you want to move

# Move the file
cp "${source}/${file_to_move}" "${destination}"


