import { Inter } from 'next/font/google'
import '.././globals.css'
import Header from '@/components/header'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Bridge',
  description: 'Generated by create next app'
}

interface RootLayoutProps {
  children: React.ReactNode
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <div className={inter.className}>
      <Header />

      {children}
    </div>
  )
}
